travis:
  secure:
    BINSTAR_TOKEN: GGHWOUqrcS/Eysjm5DRNofuAaQR6QOu9nghT6lJ495OEMrTFrWS487oam7jLql876yTLPVOxZprUYpRye2Yd/OxVh4n05WdR9qxXJDl647ISFbiSiT+tWur1LP9ePhT2N3n2+MhPiS7M9G6hO5Zz+j4gJmf9moC49hWdg55Gbr0DDmjvALGTUNBKWPWFJv0kQnsMakSYOpjBdiEjvjqBFZFAjYgwpOmEl4LqRLb86CQXQud0lU6eG1zfaYBhr3VODz6IvMCPv3p1jj45O2+AszNXQXK1f4sejnod2OD1+aCvcWEseFxR86SaUkTJhToJ4Gq+3yV+G+GzcpvIYc0lK31O1+VWXiTQLgBcnBeWhi+C9xyYrv2CmUMBVOhB2ysHiTQ+u7k+QvJXe+5USj9yTHESZvcs4zOmg6fy7+Wct2reI7K4QOjqTLIno7jZgpyrjH8YAmCz8jFH1dNAkIQVyS8KRPw93EFh23Q2i7tjGc6yic/TX9/XKhQeodS3eusQUaanUv+7qohcQ/R9gbKU/BXn2wq0vI/2Oi+6ZivqmgG5I6soYaK4W7A3iDaG2P15wW9vTXlZMKgq7K2+DliDZhI+DetUNIjf7uMXbwpvSJLvJ8+qzNM90KvyUQzzAVbxJsK1Ilmgkgr61u2EbbgyvZJcH/sb3ka81trUbBFruwU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
