travis:
  secure:
    BINSTAR_TOKEN: HQfkOrZ2U2GPnbf8DCpjp1JGsrPtUl6mruGqVMBxWsZHML1ioEzyq4GYmTTO1/fnFQaCKypfHj5b0G+LkVRh9tDoKX3RLhR0VuqHELaWYiIN5LQ6rdbxgvry1XxzwGV+kCtLRyJJ8gGPQny2cHzjkdTecFAhVxIfBh0gopwaUHr7wJTdwiWfEhbxPWNnZLbT8kV0/85OqdwUG/LThBpSMrbU7AwGp1uUbRv7UfPkX5Du6X1wXYPCbKAhrsWkVFITsxTGk67XcedvsMU6Aoc2OmvNPCAcBoCs1/R8Vdx1Q8IOdr/e2gdIEzO4wuoy8rWM6d7mOb3m4vdN07rKp1EeQJfWDAqR7COSpZW0pPKQ0LOK9YUlIegeXEgZ21JyWDk7ddOQ1mPl+XOd6E4Dw6QFmsJLUAf6nJmMEuCXH3+fyj2+WKxnLHpUMYOilrwjyvYMvKLF/GKRRdhbZeOjs+R3iHdhlb4zWrFYpz9eBXAwIYE1nhiCK5jFNE6qxEh5ZUvnEQtKPVcwLlyFACT4Szi0ErGhswrrd099Ry569gBTt8wnzKvpP4xESBKNTPkmBGgZr9q5aA/qvHO1oDwHGVU63zKXYjbuBKzgBIH24hiqxb/5muFMAC9jVS5tIldTPP/BH7u8bD7zA2bCigFFYCJLnerEiEQ8LGuBLZw15EmRPmY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
